name: Container

on:
  push:
    branches:
      - develop
      - container_test

jobs:
  build_container_and_push:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'deepmodeling'
    strategy:
      matrix:
        dockerfile: ["gnu","intel","cuda"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: registry.dp.tech
          username: ${{ secrets.DP_HARBOR_USERNAME }}
          password: ${{ secrets.DP_HARBOR_PASSWORD }}

      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          tags: |
            ghcr.io/deepmodeling/abacus-${{ matrix.dockerfile }}:latest
            registry.dp.tech/deepmodeling/abacus-${{ matrix.dockerfile }}:latest
          file: Dockerfile.${{ matrix.dockerfile }}
          cache-from: type=registry,ref=ghcr.io/deepmodeling/abacus-${{ matrix.dockerfile }}:latest
          cache-to: type=inline
          push: true
