name: Dynamic Analysis

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Do the job on the runner
    runs-on: self-hosted
    if: github.repository_owner == 'deepmodeling'
    container: ghcr.io/deepmodeling/abacus-development-kit:gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Building
        run: |
          cmake -B build -DENABLE_ASAN=1 -DBUILD_TESTING=ON -DENABLE_DEEPKS=1
          cmake --build build -j16
          cmake --install build
      - name: Testing
        run: |
          cmake --build build --target test ARGS="-V"
      - name: Publish Report to Dashboard
        uses: crazy-max/ghaction-github-pages@v2
        if: ${{ ! cancelled() }}
        with:
          target_branch: dashboard
          build_dir: html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
