name: Dynamic Analysis

on:
  schedule:
    - cron: '0 16 * * 0'
  workflow_dispatch:

jobs:
  test:
    name: Dynamic analysis
    runs-on: self-hosted
    if: github.repository_owner == 'deepmodeling'
    container: ghcr.io/deepmodeling/abacus-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Building
        run: |
          cmake -B build -DENABLE_ASAN=1 -DENABLE_DEEPKS=1 -DENABLE_LIBXC=1
          cmake --build build -j8
          cmake --install build
      - name: Testing
        run: |
          cd tests/integrate
          bash Autotest.sh -n 2 -s true
      - name: Publish Report to Dashboard
        uses: crazy-max/ghaction-github-pages@v4
        if: ${{ ! cancelled() }}
        with:
          target_branch: dashboard
          build_dir: tests/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
