name: Static Analysis

on:
  workflow_dispatch:

jobs:
  clang-tidy:
    runs-on: self-hosted
    if: github.repository_owner == 'deepmodeling'
    container: ghcr.io/deepmodeling/abacus-development-kit:gnu
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup clang-tidy
        run: |
          apt-get update && apt-get install -y --no-install-recommends clang-format clang-tidy
      - name: Generate Build Commands
        run: |
          cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=1
      - name: Checkout Changed Files
        id: files
        uses: deepmodeling/get-changed-files@master
      - name: Run clang-tidy
        run: |
          printf "%s\n" ${{ steps.files.outputs.added_modified }} | grep -E "^.*\.(cpp|h)$" > cppfiles.txt
          clang-tidy -p=build --export-fixes=diagnostics.yaml `cat cppfiles.txt`
      - name: Run clang-tidy-pr-comments action
        uses: deepmodeling/abacus-code-reviewer@master
        with:
          # The GitHub token (or a personal access token)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The path to the clang-tidy fixes generated previously
          clang_tidy_fixes: diagnostics.yaml
          # Optionally set to true if you want the Action to request
          # changes in case warnings are found
          request_changes: true
          # Optionally set the number of comments per review
          # to avoid GitHub API timeouts for heavily loaded
          # pull requests
          suggestions_per_comment: 10
