name: Integration Test and Unit Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: self-hosted
    if: github.repository_owner == 'deepmodeling'
    container: ghcr.io/deepmodeling/abacus-development-kit:gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Build
        run: |
          cmake -B build -DBUILD_TESTING=ON -DENABLE_DEEPKS=ON -DENABLE_LIBXC=ON
          cmake --build build -j8
          cmake --install build
      - name: Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '1'
        run: |
          cmake --build build --target test ARGS="-V"
