name: Integration Test and Unit Test

on:
  pull_request_target:
    branches:
      - develop
      - update_MD
      - ABACUS_2.2.0_beta
      - deepks
      - planewave
      - pw_refactor
      - TDDFT
jobs:

  test:
    name: Do the job on the runner
    runs-on: self-hosted
    container: ghcr.io/deepmodeling/abacus-development-kit:gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build and Test
        env:
          GTEST_COLOR: 'yes'
        run: |
          cmake -B build -DBUILD_TESTING=ON
          cmake --build build -j8
          cmake --install build
          cmake --build build --target test ARGS="-V"
